### ISSUE TITLE
request is deprecated and could be replaced 

### ISSUE THREAD

**Issue by volschin** [justme-1968/alexa-fhem#19]
request is now officially deprecated and produces warnings by installing.
You can see her https://github.com/request/request/issues/3142

The package could be replaced by got.
https://www.npmjs.com/package/got

**Comment by justme-1968** [comment]
maybe easier: https://github.com/postmanlabs/postman-request

**Comment by volschin** [comment]
Makes sense. We will see how long they further support their fork.

**Comment by justme-1968** [comment]
the head version has switched to postman-request. please test :)

**Comment by volschin** [comment]
Works without problems.
