### ISSUE TITLE
make FHEM Connector in others countries than Germany

### ISSUE THREAD

**Issue by moustic999** [justme-1968/alexa-fhem#20]
It would be really great to have FHEM Connector available on amazon.fr and amazon.com because switching to germany looses all others skills and feature.
If needed I can help with translation, mapping or whatever needed to achieve this.

**Comment by justme-1968** [comment]
to do this we would need translations of:

- account linking web page
- readme and other documentation for the skill that is visible in the alexa app
- at least a short howto from the wiki
- privacy statement

for each language/country the skill is to be published in.

basically no software changes are needed (besides switching the language one the account linking page) beside these translations and a first test with the skill running in english for a uk account worked perfectly fine.

unfortuantaley till now all volunteer that had started talking about this have not been heard again from :)

**Comment by gvzdus** [comment]
Well, the *strict* requirement is the privacy statement and the skill description, correct?

The account linking page for our German version has always been in English :-)

**Comment by moustic999** [comment]
> to do this we would need translations of:
> 
> * account linking web page
> * readme and other documentation for the skill that is visible in the alexa app
> * at least a short howto from the wiki
> * privacy statement
> 
> for each language/country the skill is to be published in.
> 
> basically no software changes are needed (besides switching the language one the account linking page) beside these translations and a first test with the skill running in english for a uk account worked perfectly fine.
> 
> unfortuantaley till now all volunteer that had started talking about this have not been heard again from :)

I can make that translation, at least to french ! and most probably english as well. 
Can you provide me the links where I can find original texts ?  and how to contribute ? Is it good to send you them back translated ?

**Comment by moustic999** [comment]
here is the french translation for the skill description page : 

Grace à cette skill, FHEM peut être connecté sans avoir besoin de compte développeur, d'installer un lambdas, ou d'ouvrir des ports entrant.

Une installation de FHEM fonctionnelle est nécessaire pour l'utilisation de cette skill.

Plus d'informations peuvent être trouvées ici: https://wiki.fhem.de/wiki/Alexa-FHEM-lazy

Pour trouver de l'aide via le forum, recherchez "FHEMlazy".


Where can I find privacy statement ?

I will try to translate the wiki page, at least to english. but I have to check first how to contribute to the wiki.

**Comment by justme-1968** [comment]
one more problem: i'm not sure ist the minimum that hast to be translated. it changes from skill submission to submission ...

this time i even got the notification that the url to the german documentation contains german letters :)

i have started an english version of the main page here: https://wiki.fhem.de/wiki/FHEM_Connector_for_Amazon_Alexa. maybe this stub is even enough as i also got this: 

> All of the skill’s audio and visual content must be presented in a language that matches the language of the selected locale and skill description. If you choose to upload your skill in multiple languages, it must meet one of the following requirements: 
>
> - All skill descriptions are presented in the language that corresponds to each particular locale selected; (or)
> - Skill description includes a translation in the primary local language and disclaimer stating that the skill is in another language. Example: The skill content is in German. 

i'm waiting for the latest result and then we'll se

**Comment by gvzdus** [comment]
Hi all,
especially Laurent,

It look’s like we get some drive on i8n now :-)

I wrote the privacy page, but it is outdated, and I am right in the middle of working on it and discussing it with
Rudi & Andre.

I hope to present a better version this evening. The current, outdated version is here:

https://va.fhem.de/privacy/ <https://va.fhem.de/privacy/>

I wrote it when I intended to launch „FHEM lazy“ as „one-person-show fork of Alexa-fhem“, but then Andre & I joined efforts and
made it „FHEM Connector“, hosted by the hardware of the FHEM society.
But the privacy declaration remained the same…

Keep you updated!

Best regards,


Georg

**Comment by moustic999** [comment]
@gvzdus great news ! I think the description could be also a bit changed ;-) 
I will wait you update the privacy page, then I will begin to translate it.

**Comment by gvzdus** [comment]
Dear Ludovic,

I am finished now - same URL:
https://va.fhem.de/privacy/

Yes, very ugly HTML, and feel free, to keep it even uglier. 
DSGVO is the German version of the famous GDPR - I don’t know the French analogue.

The whole thing is a mixture of a „free“ professional GDPR privacy notice, mixed together with
„A programmer want’s to tell you what he really does“.

So it *might* be more wise to „steal" some references from other French e.g. citing 
paragraphs.

In total, I don’t think it matters that much. Any court would acknowledge we are trying to 
deliver a service for free & charity instead of doing the Facebook / Google „pay with your
data“-business.

Good luck,


Georg

**Comment by moustic999** [comment]
Hello, will work on translating this.

Are you sure that it is needed in all language ? most of the skills I checked on amazon.fr have their legal notice in english ;-)

**Comment by justme-1968** [comment]
the latest results are confusing... i have asked amazon to give an exact description of what has to be translated, what has to have a disclaimer stating the only available language is german and what kann remain as is.

in any case: i have started to add your descriptions from above and i would need the french translation of the three sample sentences:

> Alexa, schalte das Licht ein
> Alexa, stelle Heizung Büro auf 21 Grad
> Alexa, wie ist die Temperatur im Kinderzimmer?
> 
> Alexa, switch on the Light
> Alexa, set Heating Office to 21 Degrees
> Alexa, what is the Temperature in the Kitchen?

**Comment by moustic999** [comment]
in french : 

 Alexa, allume la lumière
 Alexa, règle le chauffage du bureau à 21 degrés
 Alexa, quelle est la température dans la cuisine ?

but I have a doubt regarding "Kitchen" in french means "Cuisine" but in german should be "Küche" isn't it ?
What means "Kinderzimmer" ?

that's not important as these are example and all are valid ;-)

**Comment by justme-1968** [comment]
kinderzimmer is nursery but i think this is more associated with babies so children's room would be better, but i don't think this exists. and this is also the reason why the english version uses kitchen instead :)

exactly. the examples have to be correct but not identical between the languages. so thanks!

let's see what amazon answered in regard to the translations. 

and then georg hast to reactivate the demo system :)

**Comment by justme-1968** [comment]
still waiting for feedback from amazon. they are still at it.

internationalization is complicated ...

**Comment by justme-1968** [comment]
just got the answer that the privacy policy is ok as is. no mentioning of a translation.

but they want to retest the account linking. so georg... ?

**Comment by moustic999** [comment]
Hello,
Is there any progress on this ?

**Comment by justme-1968** [comment]
@gvzdus could you setup a test system for a new skill submission?

**Comment by justme-1968** [comment]
just a status update: we now have a new test system live and i have submitted the skill again (and agin) for certification. amazon is back to square one and is discussing the (missing) documentation. i have pointed them to the old discussion and the result that everything is sufficient...

**Comment by justme-1968** [comment]
@moustic999 could you please provide a french translation for the following sentence:

A list of supported SmartHome (and other) Capabilities can be found here: https://wiki.fhem.de/wiki/FHEM_Connector_für_Amazon_Alexa#Was_geht_alles_.3F

**Comment by volschin** [comment]
https://www.deepl.com/translator#en/fr/A%20list%20of%20supported%20SmartHome%20(and%20other)%20Capabilities%20can%20be%20found%20here
"Une liste des capacités SmartHome (et autres) supportées peut être trouvée ici"

**Comment by moustic999** [comment]
this translation is fine.

**Comment by justme-1968** [comment]
in the mean time i have goten 4 or 5 rejections in the mean time with varying reasons. one problem das persists is that the skill description should now contain a description of the account linking process. 

i'm still discussing with amazon if there is a way to relax some of the requirements for an open source project.

**Comment by moustic999** [comment]
What do you mean by account linking process description ? 
maybe for all translation we could have all translation files in this github, that would ease all translations .

also, is it still possible to have alexa, the old way with Lambda.js ? is there somewhere some doc for this ?

**Comment by justme-1968** [comment]
depening on the technician, the day of the week and the pase of the moon they want different things. up to the complete step by step documentation with all dependencies like it is visible in the wiki. for each language in the skill summary. i don't want to do that. also a major problem would be that for every single correction or addition (like new devices that are supported) the skill certification has to be redone. 

if at a all possible i would like to keep everything in the wiki where we can make changes without recertification.

**Comment by justme-1968** [comment]
yes. you can run everything like before as a private skill with port forwarding as described here: https://wiki.fhem.de/wiki/Alexa-Fhem

most of the screenshots are probably outdated by now but the basic setup is still the same.

**Comment by moustic999** [comment]
I will translate the wiki to french, then ;-) I'm not afraid to do it; 
But how can I provide you these translation ?

**Comment by justme-1968** [comment]
just crate a wiki account for yourself and do it there. 

but maybe wait a little for the latest amazon answers.

**Comment by justme-1968** [comment]
still dikussing with amazon...

but: the german skill page now shows the current description and states that the skill is also available in other languages: german, english (us and gb) and french.

i can't veryify this as my echos are all linked to a german account and i get redirected to the german page if i try to open the english or french alexa pages. despite also having a uk and us amazon account.

also: i'm not sure if you have to have a french or english account or if it is enough to change the language in the echo settings. the skill page says to with the echo language, but if i do this i get a warning that the echo language is different from the account language.

**Comment by moustic999** [comment]
I just searched over fhem on amazon.fr but nothing yet.
I looked also on amazon.de and i find it easily, But it Shows only Deutsch (DE)...
[https://www.amazon.de/Andre-Schr%C3%B6ter-FHEM-Connector/dp/B07MM63ZY3/ref=sr_1_1?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=703MMFCY0G91&dchild=1&keywords=fhem+connector&qid=1591025095&s=digital-skills&sprefix=fhem%2Calexa-skills%2C158&sr=1-1](url)

**Comment by justme-1968** [comment]
ok. then then my account musst be linked to the developer account. sorry for the false alarm.

**Comment by justme-1968** [comment]
it is done!

the skill is live for german, english (us and uk) and french.

**Comment by gvzdus** [comment]
Congratulations!!!

I will leave the test instance up for some days before I shut it down.

**Comment by moustic999** [comment]
Many thanks to all !
It is working fine ! I can switch on : off my KNX lights with Alexa !



Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : gvzdus<mailto:notifications@github.com>
Envoyé le :vendredi 12 juin 2020 10:11
À : justme-1968/alexa-fhem<mailto:alexa-fhem@noreply.github.com>
Cc : Ludovic Laurent<mailto:moustic999@msn.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [justme-1968/alexa-fhem] make FHEM Connector in others countries than Germany (#20)

Congratulations!!!

I will leave the test instance up for some days before I shut it down.
