### ISSUE TITLE
Alexa Interface not reported in capabilities during discovery

### ISSUE THREAD

**Issue by moustic999** [justme-1968/alexa-fhem#21]
i see during discovery that Alexa interface is not present in capabilities 
`            {
              "type": "AlexaInterface",
              "interface": "Alexa",
              "version": "3"
            }
`
While it is not mandatory, it should be explicitely defined as per amazon documentation :
[https://developer.amazon.com/fr-FR/docs/alexa/device-apis/alexa-interface.html](url)

**Comment by justme-1968** [comment]
are you sure?

i can see it in my logs and also in the example you send with the last fhem pm.

**Comment by moustic999** [comment]
yes, I'm sure ;-) 
it is missing in the example I sent you 
search for  the string  > "interface": "Alexa" <, it is nowhere; it should be present for each endpoint in capabilities.
see example  at https://developer.amazon.com/fr-FR/docs/alexa/device-apis/alexa-interface.html
there is 1 endpoint which has 2 capabilities. the second one ( with "interface": "Alexa" ) is never in fhem discovery

**Comment by justme-1968** [comment]
now i see. you are right. it is missing.

i have added it to the latest version.

un fortunately there is no api changeling. i'd love to know if i have just missed it or if it is a later addition to the documentation. during a problem report for the semantics part amazon noticed a typo in my json message, but not the missing alexa interface.

**Comment by gvzdus** [comment]
Hi Justme,

might I shut down the test instance now? Or do you expect further tests by Amazon?
Just keen to save some money - I might take it up another time again.

Cheers, Georg

**Comment by justme-1968** [comment]
sorry for forgetting this. yes. the test instance is not needed anymore. until we decide to certify again :)

thanks
  andre
