### ISSUE TITLE
Informationen über Port :3000 abrufen

### ISSUE THREAD

**Issue by sidey79** [justme-1968/alexa-fhem#25]
Ist es möglich, Informationen zu alexa-fhem über den Port 3000 abzurufen?

Im quellcode habe ich gesehen dass favicon.ico speziell behandelt wird, aber andere Request URLs konnte ich nicht identifizieren.
Hintergrund meiner Frage ist, dass das alexa FHEM Modul aktuell nicht erkennen kann, ob alexa-fhem läuft, wenn alexa-fhem z.B. in einem anderen docker container ausgeführt wird.

Wenn man das aber über http abrufen könnte, ließe sich das ja in das Modul durchaus relativ leicht einbauen glaube ich.

**Comment by volschin** [comment]
Wie genau willst Du es denn wissen? Du kannst doch den Port 3000 aufrufen und bekommst ein JSON zurück. Mir reicht für ein healthy die Fehlermeldung. Wenn Du es noch besser machen willst, müsstest Du Dir ein valides JSON bauen.
Alternativ wäre natürlich ein /health möglich, wo man dann überlegen müsste, was die Rückgabe alles geprüft haben soll.

**Comment by sidey79** [comment]
Mich würde interessieren, ob die Verbindung zum Vereinsserver steht und welche alexa-fhem Version im Einsatz ist.

Wenn ich wüsste was im Json steht, könnte ich das natürlich auch bauen, aber ein /health ohne Parameter wäre die einfachste Variante.

**Comment by volschin** [comment]
So sieht das JSON aus:
{"header":{"namespace":"Alexa.ConnectedHome.Control","name":"UnsupportedOperationError","payloadVersion":"2","messageId":"687e3e02-xxxx-4b9f-9c35-54fd31f2c196"},"payload":{}}

**Comment by sidey79** [comment]
@volschin 
Wenn ich das recht verstehe, dann ist das ja die Antwort. Meine Frage Bezüglich des JSONs war eher, was müsste ich übergeben, damit ich entsprechende Informationen zurück bekomme. Aus dem Quellcode konnte ich den Aufbau jetzt nicht einfach reproduzieren.

**Comment by justme-1968** [comment]
alle informationen die du suchst werden auf stdout ausgegeben und vom fhem modul ausgewertet und angezeigt so lange du den vorgesehenen weg nimmst und alexa-fhem durch das fhem modul startest. 

wenn du aus welchen gründen auch immer einen sonderweg gehen willst musst du stdout selber auswerten.

der port 3000 ist für den betrieb von alexa-fhem mit port forwarding und ohne vereinsserver. 

was du hier an json übergeben kannst findest du in der skill api dokumentation. 

alexa-fhem kann zwar die port 3000 variante und die vereinsserver variante gleichzeitig nutzen, die eine seite hat aber keinerlei informationen über die andere.

**Comment by sidey79** [comment]
Das mit dem vorgesehenen weg verstehe ich nicht.
Alexa-Fhem kann und wird durch einen docker Container gestartet. Da ist kein FHEM Modul beteiligt.

Dass der Server auf Port 3000 die gewünschten Infos nicht liefert hatte ich mir schon gedacht.
Was gibt es denn für Möglichkeiten eine Schnittstelle dafür anzubieten um das über eine http(s) Verbindung abzufragen.

**Comment by justme-1968** [comment]
der vorgesehene weg ist das alexa-fhem auf dem gleichen host läuft wie fhem und das alexa modul in fhem alexa-fhem per fork/exec startet. alternativ kann ein anderer host verwendet werden wenn fhem per ssh zugriff zum starten hat.

die schnittstelle ist stdout/stdin von alexa-fhem.

**Comment by sidey79** [comment]
Ich verstehe was Du meinst, allerdings ist das beides für docker eher ungeeignet und die Docker Variante wird ja durchaus angeboten und funktioniert bis auf die Information welcher deamon läuft ganz gut:

https://github.com/fhem/alexa-fhem-docker

Jetzt irgendein wrapper um das alexa-fhem zu bauen, welches stdout einem anderen container zur Verfügung stellt ist nicht unbedingt das, was ich mir vorgestellt hatte.

**Comment by justme-1968** [comment]
die docker variante wird weder von mir angeboten noch unterstützt.  und wie du siehst funktioniert es je eben nicht... :)

ich halte docker für den falschen ansatz. gerade weil das fhem modul explizit das starten und stoppen von alexa-fhem eingebaut hat ist es kontraproduktiv einen getrennten docker containers dazu zu verwenden.

ich verstehe nicht was du dir davon versprichst.

wenn es wirklich docker sein muss: was spricht denn dagegen fhemn und alexa-fhem im gleichen container laufen zu lassen?

oder alternativ: eine richtige virualisierung zu verwenden?

**Comment by sidey79** [comment]
Ich will jetzt keine Grundsatzdiskussion entfachen, aber FHEM läuft auf Perl und alexa-fhem unter nodejs. Falsch ist die docker Virtualisierung nicht, keine Ahnung warum Du das so bewertest.

Alexa-Fhem kann problemlos von einem Container gestartet werden und zu Vereinsserver und Fhem Container kommunizieren.
Nur FHEM findet keine Schnittstelle zu Alexa-Fhem. Das über SSH ist doch keine Schnittstelle zur Anwendung, das ist doch mehr eine Notlösung weil es keinen Endpunkt von der Applikation gibt.

Alexa-Fhem in einem Perl Container auf verschiedensten Plattformen anzubieten habe ich aufgegeben, da es zu viel Probleme bereitet.
Das ganze Problem mit dem Aktualisieren lasse ich mal beiseite, denn in getrennten Containern ist es wesentlich einfacher. Ich aktualisiere den fhem-alexa-container wenn es ein neues node oder Alexa-Fhem gibt. Obendrein sollte sich jeder bewusst machen, dass es eine Verbindung zwischen Alexa-fhem und dem Vereinsserver gibt. Sowas gehört in der Regel getrennt vom internen Systemen was durch Alexa-Fhem auch ganz gut funktioniert.

Wie auch immer, dass docker von Dir nicht unterstützt wird habe ich herausgelesen auch wenn es den Schalter dockerDetatched ja gibt.
Bleibt also nur die Nutzer im Regen stehen zu lassen wenn sie Docker verwenden. :-(

**Comment by justme-1968** [comment]
und aus welchem grund hat die spräche in der etwas implementiert ist etwas mit der Umgebung zu tun in der man es laufen lässt?

eben weil es keine grundsatz diskussion sein sollte habe ich nicht zu docker gesagt. aber vielleicht erklärt es das ganze für dich etwas: ich halte docker für den falschen ansatz. virtualisierung sollte transparent sein und sich exakt genau so verhalten wie ein echtes system. das ist bei docker an allen möglichen ecken und enden nicht der fall. docker macht im support und bei jedem der sich nicht damit nicht zu 100% auskennt probleme.

die schnittstelle zwischen alexa-fhem und alexa ist stdio. sie funktioniert in beide richtungen und ist robust gegen alle möglichen probleme. das dies out of the box auch über ssh möglich ist ist ein plus und keine notlösung.

dockerDetatched gibt es weil es wegen docker eigenheiten sonst garnicht laufen würde. wieder ein beispiel mehr dafür das docker alles andere als transparent ist. sowohl das in docker laufende system als auch die kommunikation zwischen containern und das start system müssen angepasst werden. und das ist einfach mist. die probleme die du oben beschreibst zeigen genau das auch. und der update sollte gerade nicht außen vor gelassen werden. gerade bei fhem und alexa-fhem die recht gut gekapselt sind ist ein update direkt eingebaut bzw. vorgesehen und wird durch docker nur komplizierter. das gleiche gilt für den backup.

es tut mir leid das ich dir nicht mehr helfen kann. aber um auch noch energie in eine schnittstelle und/oder ein api zu stecken das ich weder selbst verwende, das nicht nötig ist weil es bereits einen funktionierenden und unterstützten weg gibt und das am ende dann doch wieder eine halbherzige krücke für einen von grund auf falschen ansatz implementiert geht zeitlich einfach nicht. 

wenn du einen patch hast der das alles implementiert und sicherstellt das es inklusive starten und stoppen aus fhem heraus mit status anzeige funktioniert schaue ich es mir gerne an.
