### ISSUE TITLE
2 fhem-connections with the same device-names

### ISSUE THREAD

**Issue by vafgoettlich** [justme-1968/alexa-fhem#29]
Dear Maintainer,

first of all I like to thank you for your work. I am running 2 fhem-instances (each on a different floor). I'm having a dummy-devices on both of them called Alle_Rolllaeden (all_shutters in english) to close / open all of them at the same time.

I have added a alexaName Attribute but unfortunately I cannot add the second one because:
```
[7/26/2024, 6:59:11 AM] [OG] Alle_Rolllaeden is already published
[7/26/2024, 6:59:11 AM] [OG] no device created for Alle_Rolllaeden (dummy)
```

Maybe the connection-Name or something like that should be added to identify the device, or am I doing things wrong?

**Comment by vafgoettlich** [comment]
Thanks for the fast response. About your question why I am operating 2 fhem-instances I would like to describe the setup a bit:
- I have one unipi neuron: https://www.unipi.technology/ in the breakerbox of each floor
- nearly everything of my devices are hardwired to that unipi-device
- on the device I am running evok + fhem to use the ports
Now the reason:
- Currently we are using both floors for our family, but the house is build to have each floor as a seperate flat (i.E. for rent). So for future maybe the networks will be splitted
- I want to reduce the risk of a hardware-/software-/...failure. If anything fails on floor 1 floor 2 has still working switches, lights and shutters
- I do not have the usecase (expect alexa) to automate things together in floor 1 and floor 2 ;-)

**Comment by justme-1968** [comment]
that makes sense :)
thanks
